server:
  port: 8021
spring:
  application:
    name: linze-turbine-service
turbine:
  aggregator:
    clusterConfig: default
  appConfig: linze-view-service-feign  ### 配置Eureka中的serviceId列表，表明监控哪些服务
  clusterNameExpression: new String("default")
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
